### ISSUE TITLE
IAR compiling fails when using mbed-os

### ISSUE THREAD

**Issue by jupe** [PelionIoT/nanostack-libservice#39]
Application: [mbed-os-cliapp](https://github.com/armmbed/mbed-os-cliapp)
Toolchain: IAR
Platform: K64F
problematic function: https://github.com/ARMmbed/nanostack-libservice/blob/0d5561de6091d24cf3b8c12cb91196a3e61cdd28/source/IPv6_fcf_lib/ip_fsc.c#L29

```
Compile: ip_fsc.c
[Error] ip_fsc.h@25: [Pe411]: a parameter is not allowed
[Error] ip_fsc.h@27: [Pe411]: a parameter is not allowed
[Error] ip_fsc.c@29: [Pe411]: a parameter is not allowed
[Error] ip_fsc.c@78: [Pe411]: a parameter is not allowed
  extern uint16_t ip_fcf_v(uint_fast8_t count, const ns_iovec_t vec[static count]);
```

@yogpan01 @teetak01: just in case..

**Comment by SeppoTakalo** [comment]
Platform and application?

**Comment by kjbracey-arm** [comment]
Would be fixed by turning on variable length arrays. --vla option to the compiler.

**Comment by jupe** [comment]
so this should be fixed in `mbed-cli` / building tools ?

**Comment by jupe** [comment]
could you raise an issue to `mbed-cli` because you probably understand this better..

**Comment by kjbracey-arm** [comment]
Maybe. We don't actually use variable-length arrays afaik (which maybe have run-time performance impact), but we do use variably-modified types and declarations. The same switch controls both.

All our compilers do support VLAs, it's just they're not on by default in IAR.

**Comment by kjbracey-arm** [comment]
Submitted PR: https://github.com/mbedmicro/mbed/pull/1985

Could you check if that minor patch resolves the issue?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2712

**Comment by SeppoTakalo** [comment]
This need re-verification now that fixes are merged.

**Comment by SeppoTakalo** [comment]
@jupe Please verify and close, if fixed.

**Comment by TuomoHautamaki** [comment]
@jupe Please verify and close, if fixed.

**Comment by TuomoHautamaki** [comment]
@jupe Please verify and close, if fixed.
